import { deterministicUuid } from "./uuid"
import type { CriminalRecord } from "./types"

export type { CriminalRecord }

interface RawCriminal extends Omit<CriminalRecord, "uuid"> {}

const RAW: RawCriminal[] = [
  {
    id: "crm-tatarnikov",
    regNumber: "ОС-2024-11428",
    fio: "Татарников Денис Романович",
    birth: "07.05.1989",
    photo: "/convict-1.jpg",
    article: "ст. 161 ч. 2 УК РФ",
    crimeType: "Грабёж",
    sentence: "5 лет лишения свободы, общий режим",
    facility: "ИК-6 ГУФСИН по Иркутской обл.",
    startDate: "12.04.2024",
    endDate: "11.04.2029",
    recidivist: true,
    status: "Отбывает наказание",
  },
  {
    id: "crm-shergunov",
    regNumber: "ОС-2025-02214",
    fio: "Шергунов Всеволод Маркович",
    birth: "23.10.1979",
    photo: "/convict-2.jpg",
    article: "ст. 228 ч. 2 УК РФ",
    crimeType: "Наркотики",
    sentence: "4 года лишения свободы, общий режим",
    facility: "ИК-3 УФСИН по Тульской обл.",
    startDate: "08.07.2025",
    endDate: "07.07.2029",
    recidivist: false,
    status: "Отбывает наказание",
  },
  {
    id: "crm-yalimov",
    regNumber: "ОС-2025-08772",
    fio: "Ялымов Фёдор Иванович",
    birth: "30.01.1999",
    photo: "/convict-3.jpg",
    article: "ст. 158 ч. 2 УК РФ",
    crimeType: "Кража",
    sentence: "2 года 6 мес. лишения свободы, общий режим",
    facility: "ИК-9 ГУФСИН по Кемеровской обл.",
    startDate: "21.09.2025",
    endDate: "20.03.2028",
    recidivist: false,
    status: "Отбывает наказание",
  },
  {
    id: "crm-krylov",
    regNumber: "ОС-2022-МО-04711-1",
    fio: "Крылов Николай Андреевич",
    birth: "1989 г.р.",
    photo: "/suspect-front.png",
    article: "ст. 158 ч. 3 УК РФ",
    crimeType: "Кража",
    sentence: "4 года лишения свободы, общий режим",
    facility: "ИК-2 УФСИН по Московской обл.",
    startDate: "—",
    endDate: "—",
    recidivist: true,
    status: "Отбывает наказание",
  },
  {
    id: "crm-bazhukov",
    regNumber: "ОС-2023-04519",
    fio: "Бажуков Виталий Леонидович",
    birth: "12.06.1972",
    photo: "/convict-1.jpg",
    article: "ст. 105 ч. 1 УК РФ",
    crimeType: "Убийство",
    sentence: "10 лет лишения свободы, строгий режим",
    facility: "ИК-15 ГУФСИН по Свердловской обл.",
    startDate: "03.11.2023",
    endDate: "02.11.2033",
    recidivist: false,
    status: "Отбывает наказание",
  },
  {
    id: "crm-malkina",
    regNumber: "ОС-2024-07788",
    fio: "Малкина Эльза Григорьевна",
    birth: "27.02.1986",
    photo: "/convict-2.jpg",
    article: "ст. 159 ч. 4 УК РФ",
    crimeType: "Мошенничество",
    sentence: "6 лет лишения свободы, общий режим",
    facility: "ИК-2 ГУФСИН по Республике Мордовия (женская)",
    startDate: "14.08.2024",
    endDate: "13.08.2030",
    recidivist: true,
    status: "Отбывает наказание",
  },
  {
    id: "crm-petrov",
    regNumber: "ОС-2022-12001",
    fio: "Петров Аким Никитович",
    birth: "06.09.1965",
    photo: "/convict-3.jpg",
    article: "ст. 162 ч. 2 УК РФ",
    crimeType: "Разбой",
    sentence: "8 лет лишения свободы, строгий режим",
    facility: "ИК-12 УФСИН по Челябинской обл.",
    startDate: "20.05.2022",
    endDate: "19.05.2030",
    recidivist: true,
    status: "Этап",
  },
  {
    id: "crm-shilyaev",
    regNumber: "ОС-2021-08819",
    fio: "Шиляев Никита Корнеевич",
    birth: "11.04.1995",
    photo: "/convict-1.jpg",
    article: "ст. 264 ч. 4 УК РФ",
    crimeType: "ДТП",
    sentence: "5 лет лишения свободы, колония-поселение",
    facility: "КП-2 УФСИН по Тверской обл.",
    startDate: "14.10.2021",
    endDate: "13.10.2026",
    recidivist: false,
    status: "Освобождён условно",
  },
  {
    id: "crm-rybnikov",
    regNumber: "ОС-2023-09155",
    fio: "Рыбников Олесь Серафимович",
    birth: "29.12.1968",
    photo: "/convict-2.jpg",
    article: "ст. 290 ч. 5 УК РФ",
    crimeType: "Коррупция",
    sentence: "9 лет лишения свободы, строгий режим",
    facility: "ИК-7 УФСИН по Тверской обл.",
    startDate: "07.07.2023",
    endDate: "06.07.2032",
    recidivist: false,
    status: "Отбывает наказание",
  },
  {
    id: "crm-orlinkov",
    regNumber: "ОС-2020-04488",
    fio: "Орлинков Свят Викторович",
    birth: "21.03.1958",
    photo: "/convict-3.jpg",
    article: "ст. 213 ч. 1 УК РФ",
    crimeType: "Хулиганство",
    sentence: "3 года лишения свободы, общий режим",
    facility: "ИК-9 УФСИН по Ивановской обл.",
    startDate: "11.02.2020",
    endDate: "10.02.2023",
    recidivist: true,
    status: "Отбыл наказание",
  },
  {
    id: "crm-troyanov",
    regNumber: "ОС-2024-02201",
    fio: "Троянов Артемий Альбертович",
    birth: "07.10.1991",
    photo: "/convict-1.jpg",
    article: "ст. 228.1 ч. 4 УК РФ",
    crimeType: "Наркотики",
    sentence: "12 лет лишения свободы, строгий режим",
    facility: "ИК-1 ГУФСИН по Красноярскому краю",
    startDate: "18.06.2024",
    endDate: "17.06.2036",
    recidivist: true,
    status: "Отбывает наказание",
  },
  {
    id: "crm-vasiliev",
    regNumber: "ОС-2025-11108",
    fio: "Васильев Артём Феофанович",
    birth: "30.05.1980",
    photo: "/convict-2.jpg",
    article: "ст. 166 ч. 1 УК РФ",
    crimeType: "Угон",
    sentence: "1 год 6 мес. лишения свободы, общий режим",
    facility: "ИК-3 УФСИН по Калужской обл.",
    startDate: "12.11.2025",
    endDate: "11.05.2027",
    recidivist: false,
    status: "Отбывает наказание",
  },
  {
    id: "crm-piskunov",
    regNumber: "ОС-2022-00177",
    fio: "Пискунов Лев Ярославович",
    birth: "16.08.1977",
    photo: "/convict-3.jpg",
    article: "ст. 158 ч. 4 УК РФ",
    crimeType: "Кража",
    sentence: "7 лет лишения свободы, строгий режим",
    facility: "ИК-5 ГУФСИН по Кемеровской обл.",
    startDate: "04.01.2022",
    endDate: "03.01.2029",
    recidivist: true,
    status: "Отбывает наказание",
  },
  {
    id: "crm-bunkin",
    regNumber: "ОС-2023-08833",
    fio: "Бункин Степан Робертович",
    birth: "14.11.1996",
    photo: "/convict-1.jpg",
    article: "ст. 161 ч. 1 УК РФ",
    crimeType: "Грабёж",
    sentence: "3 года лишения свободы, общий режим",
    facility: "ИК-2 УФСИН по Псковской обл.",
    startDate: "27.09.2023",
    endDate: "26.09.2026",
    recidivist: false,
    status: "Освобождён условно",
  },
]

export const CRIMINALS_SEED: CriminalRecord[] = RAW.map((c) => ({
  ...c,
  uuid: deterministicUuid(`criminal:${c.id}`),
}))
